// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from 'react';
import { PageParamsProvider as PageParamsProvider__ } from '@plasmicapp/react-web/lib/host';
import GlobalContextsProvider from '../components/plasmic/cruise_crew_iq/PlasmicGlobalContextsProvider';

import { PlasmicBooking } from '../components/plasmic/cruise_crew_iq/PlasmicBooking';
import { useRouter } from 'next/router';

function Booking() {
  return (
    <GlobalContextsProvider>
      <PageParamsProvider__
        route={useRouter()?.pathname}
        params={useRouter()?.query}
        query={useRouter()?.query}
      >
        <PlasmicBooking />
      </PageParamsProvider__>
    </GlobalContextsProvider>
  );
}

export default Booking;
