// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: r6SzurXsLMJXPqEBWV3sKk
// Component: Gu2oVihXfE2_

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";
import * as plasmicAuth from "@plasmicapp/react-web/lib/auth";
import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";

import Navbar from "../../Navbar"; // plasmic-import: 8V9ZObcqgPEi/component
import Footer from "../../Footer"; // plasmic-import: tfXGV_GyVRZh/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: r6SzurXsLMJXPqEBWV3sKk/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: Gu2oVihXfE2_/css

import MakiSwimming0Icon from "./icons/PlasmicIcon__MakiSwimming0"; // plasmic-import: pLOxRINKqAi5/icon
import Vector7Icon from "./icons/PlasmicIcon__Vector7"; // plasmic-import: B1EEi84XW3H-/icon
import Vector8Icon from "./icons/PlasmicIcon__Vector8"; // plasmic-import: AzVElw8aH14T/icon
import Vector9Icon from "./icons/PlasmicIcon__Vector9"; // plasmic-import: DCTaj4xsBylx/icon
import Vector10Icon from "./icons/PlasmicIcon__Vector10"; // plasmic-import: 1Yh_7-tY4G1d/icon
import Vector11Icon from "./icons/PlasmicIcon__Vector11"; // plasmic-import: ojBJgKCDNwjO/icon
import Vector12Icon from "./icons/PlasmicIcon__Vector12"; // plasmic-import: DYxpmpV_kkRY/icon
import Vector13Icon from "./icons/PlasmicIcon__Vector13"; // plasmic-import: hTfq5-pOe_yN/icon
import Group10Icon from "./icons/PlasmicIcon__Group10"; // plasmic-import: mXysGID4_YRc/icon
import Vector15Icon from "./icons/PlasmicIcon__Vector15"; // plasmic-import: f7hIedboTuPX/icon
import Vector14Icon from "./icons/PlasmicIcon__Vector14"; // plasmic-import: Vt0OsREjETaB/icon

createPlasmicElementProxy;

export type PlasmicHomepage__VariantMembers = {};
export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  home?: Flex__<"div">;
  navbar?: Flex__<typeof Navbar>;
  group24?: Flex__<"div">;
  frame30?: Flex__<"div">;
  frame29?: Flex__<"div">;
  group29?: Flex__<"div">;
  bookBtn?: Flex__<"a"> & Partial<LinkProps>;
  rectangle5?: Flex__<"div">;
  frame25?: Flex__<"div">;
  frame281?: Flex__<"div">;
  row1?: Flex__<"div">;
  facility1?: Flex__<"div">;
  rectangle8?: Flex__<"div">;
  group9?: Flex__<"div">;
  facility7?: Flex__<"div">;
  rectangle9?: Flex__<"div">;
  group10?: Flex__<"div">;
  facility8?: Flex__<"div">;
  rectangle10?: Flex__<"div">;
  group11?: Flex__<"div">;
  facility9?: Flex__<"div">;
  rectangle11?: Flex__<"div">;
  group12?: Flex__<"div">;
  row2?: Flex__<"div">;
  facility10?: Flex__<"div">;
  rectangle12?: Flex__<"div">;
  group13?: Flex__<"div">;
  facility11?: Flex__<"div">;
  rectangle13?: Flex__<"div">;
  group14?: Flex__<"div">;
  facility12?: Flex__<"div">;
  rectangle14?: Flex__<"div">;
  group15?: Flex__<"div">;
  facility13?: Flex__<"div">;
  rectangle15?: Flex__<"div">;
  group16?: Flex__<"div">;
  viewRooms?: Flex__<"div">;
  title?: Flex__<"div">;
  rectangle16?: Flex__<"div">;
  roomsType?: Flex__<"div">;
  room1?: Flex__<"div">;
  rectangle17?: Flex__<"div">;
  room2?: Flex__<"div">;
  rectangle18?: Flex__<"div">;
  room4?: Flex__<"div">;
  rectangle19?: Flex__<"div">;
  frame27?: Flex__<"div">;
  frame4?: Flex__<"div">;
  testimony1?: Flex__<"div">;
  frame282?: Flex__<"div">;
  rating?: Flex__<"div">;
  rectangle20?: Flex__<"div">;
  frame283?: Flex__<"div">;
  theServiceAtTheHotelMonteleoneWasExceptionalThereWasAbsolutelyNoIssueThatWasNotAddressedTimelyAndWithSatisfactoryResultsWeWereParticularyImpressedWithHowTheHotelStaffAnticipatedOurNeedsPeriodicallyComingByTheBoardRoomToCheckWithUsNumerousConferenceAttendeesCommentedOnTheQualityOfTheFoodTheQualityOfTheServiceAndOverallPositiveAttitudeTowardTheConferenceSiteParticularNoteworthyIsTheLongevityOfTheStaffAndThatSenseOfInvestmentInTheSuccessOfEveryEventIUsuallyOfferSuggestionsForImprovementsPartOfBeingAMarketingProfessorButThereIsAbsolutelyNothingThatCouldBeImprovedYouHaveSetTheBarVeryHigh?: Flex__<"div">;
  frame284?: Flex__<"div">;
  testimony4?: Flex__<"div">;
  frame285?: Flex__<"div">;
  rating2?: Flex__<"div">;
  rectangle21?: Flex__<"div">;
  frame286?: Flex__<"div">;
  theServiceAtTheHotelMonteleoneWasExceptionalThereWasAbsolutelyNoIssueThatWasNotAddressedTimelyAndWithSatisfactoryResultsWeWereParticularyImpressedWithHowTheHotelStaffAnticipatedOurNeedsPeriodicallyComingByTheBoardRoomToCheckWithUsNumerousConferenceAttendeesCommentedOnTheQualityOfTheFoodTheQualityOfTheServiceAndOverallPositiveAttitudeTowardTheConferenceSiteParticularNoteworthyIsTheLongevityOfTheStaffAndThatSenseOfInvestmentInTheSuccessOfEveryEventIUsuallyOfferSuggestionsForImprovementsPartOfBeingAMarketingProfessorButThereIsAbsolutelyNothingThatCouldBeImprovedYouHaveSetTheBarVeryHigh2?: Flex__<"div">;
  frame287?: Flex__<"div">;
  testimony5?: Flex__<"div">;
  frame288?: Flex__<"div">;
  rating3?: Flex__<"div">;
  rectangle22?: Flex__<"div">;
  frame289?: Flex__<"div">;
  theServiceAtTheHotelMonteleoneWasExceptionalThereWasAbsolutelyNoIssueThatWasNotAddressedTimelyAndWithSatisfactoryResultsWeWereParticularyImpressedWithHowTheHotelStaffAnticipatedOurNeedsPeriodicallyComingByTheBoardRoomToCheckWithUsNumerousConferenceAttendeesCommentedOnTheQualityOfTheFoodTheQualityOfTheServiceAndOverallPositiveAttitudeTowardTheConferenceSiteParticularNoteworthyIsTheLongevityOfTheStaffAndThatSenseOfInvestmentInTheSuccessOfEveryEventIUsuallyOfferSuggestionsForImprovementsPartOfBeingAMarketingProfessorButThereIsAbsolutelyNothingThatCouldBeImprovedYouHaveSetTheBarVeryHigh3?: Flex__<"div">;
  frame290?: Flex__<"div">;
  footer?: Flex__<typeof Footer>;
};

export interface DefaultHomepageProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"home"}
          data-plasmic-override={overrides.home}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.home
          )}
        >
          <Navbar
            data-plasmic-name={"navbar"}
            data-plasmic-override={overrides.navbar}
            className={classNames("__wab_instance", sty.navbar)}
          />

          <Stack__
            as={"div"}
            data-plasmic-name={"group24"}
            data-plasmic-override={overrides.group24}
            hasGap={true}
            className={classNames(projectcss.all, sty.group24)}
          >
            <Stack__
              as={"div"}
              data-plasmic-name={"frame30"}
              data-plasmic-override={overrides.frame30}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame30)}
            >
              <Stack__
                as={"div"}
                data-plasmic-name={"frame29"}
                data-plasmic-override={overrides.frame29}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame29)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__pk4G
                  )}
                >
                  {"Kivu Queen"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__cnzi8
                  )}
                >
                  {"Hotel for every \nmoment rich in\nemotion"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__a16Ml
                  )}
                >
                  {"Every moment feels like the first time\nin paradise view"}
                </div>
              </Stack__>
              <div
                data-plasmic-name={"group29"}
                data-plasmic-override={overrides.group29}
                className={classNames(projectcss.all, sty.group29)}
              >
                <Stack__
                  as={PlasmicLink__}
                  data-plasmic-name={"bookBtn"}
                  data-plasmic-override={overrides.bookBtn}
                  hasGap={true}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.bookBtn
                  )}
                  component={Link}
                  onClick={async event => {
                    const $steps = {};

                    $steps["goToBooking"] = true
                      ? (() => {
                          const actionArgs = { destination: `/booking` };
                          return (({ destination }) => {
                            if (
                              typeof destination === "string" &&
                              destination.startsWith("#")
                            ) {
                              document
                                .getElementById(destination.substr(1))
                                .scrollIntoView({ behavior: "smooth" });
                            } else {
                              __nextRouter?.push(destination);
                            }
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["goToBooking"] != null &&
                      typeof $steps["goToBooking"] === "object" &&
                      typeof $steps["goToBooking"].then === "function"
                    ) {
                      $steps["goToBooking"] = await $steps["goToBooking"];
                    }
                  }}
                  platform={"nextjs"}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kxrld
                    )}
                  >
                    {"Book now"}
                  </div>
                </Stack__>
              </div>
            </Stack__>
            <div
              data-plasmic-name={"rectangle5"}
              data-plasmic-override={overrides.rectangle5}
              className={classNames(projectcss.all, sty.rectangle5)}
            />
          </Stack__>
          <Stack__
            as={"div"}
            data-plasmic-name={"frame25"}
            data-plasmic-override={overrides.frame25}
            hasGap={true}
            className={classNames(projectcss.all, sty.frame25)}
          >
            <Stack__
              as={"div"}
              data-plasmic-name={"frame281"}
              data-plasmic-override={overrides.frame281}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame281)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__hv3Qq
                )}
              >
                {"Our Facilities"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__sIjji
                )}
              >
                {"We offer modern (5 star) hotel facilities for your comfort."}
              </div>
            </Stack__>
            <Stack__
              as={"div"}
              data-plasmic-name={"row1"}
              data-plasmic-override={overrides.row1}
              hasGap={true}
              className={classNames(projectcss.all, sty.row1)}
            >
              <div
                data-plasmic-name={"facility1"}
                data-plasmic-override={overrides.facility1}
                className={classNames(projectcss.all, sty.facility1)}
              >
                <div
                  data-plasmic-name={"rectangle8"}
                  data-plasmic-override={overrides.rectangle8}
                  className={classNames(projectcss.all, sty.rectangle8)}
                />

                <div
                  data-plasmic-name={"group9"}
                  data-plasmic-override={overrides.group9}
                  className={classNames(projectcss.all, sty.group9)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___7KP
                    )}
                  >
                    {"Swimming Pool"}
                  </div>
                  <MakiSwimming0Icon
                    className={classNames(projectcss.all, sty.svg__wuXev)}
                    role={"img"}
                  />
                </div>
              </div>
              <div
                data-plasmic-name={"facility7"}
                data-plasmic-override={overrides.facility7}
                className={classNames(projectcss.all, sty.facility7)}
              >
                <div
                  data-plasmic-name={"rectangle9"}
                  data-plasmic-override={overrides.rectangle9}
                  className={classNames(projectcss.all, sty.rectangle9)}
                />

                <div
                  data-plasmic-name={"group10"}
                  data-plasmic-override={overrides.group10}
                  className={classNames(projectcss.all, sty.group10)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__r2XnH
                    )}
                  >
                    {"Wifi"}
                  </div>
                  <Vector7Icon
                    className={classNames(projectcss.all, sty.svg___38JkS)}
                    role={"img"}
                  />
                </div>
              </div>
              <div
                data-plasmic-name={"facility8"}
                data-plasmic-override={overrides.facility8}
                className={classNames(projectcss.all, sty.facility8)}
              >
                <div
                  data-plasmic-name={"rectangle10"}
                  data-plasmic-override={overrides.rectangle10}
                  className={classNames(projectcss.all, sty.rectangle10)}
                />

                <div
                  data-plasmic-name={"group11"}
                  data-plasmic-override={overrides.group11}
                  className={classNames(projectcss.all, sty.group11)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__nYXR
                    )}
                  >
                    {"Breakfast"}
                  </div>
                  <Vector8Icon
                    className={classNames(projectcss.all, sty.svg__zOgOi)}
                    role={"img"}
                  />
                </div>
              </div>
              <div
                data-plasmic-name={"facility9"}
                data-plasmic-override={overrides.facility9}
                className={classNames(projectcss.all, sty.facility9)}
              >
                <div
                  data-plasmic-name={"rectangle11"}
                  data-plasmic-override={overrides.rectangle11}
                  className={classNames(projectcss.all, sty.rectangle11)}
                />

                <div
                  data-plasmic-name={"group12"}
                  data-plasmic-override={overrides.group12}
                  className={classNames(projectcss.all, sty.group12)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__vsomC
                    )}
                  >
                    {"Gym"}
                  </div>
                  <Vector9Icon
                    className={classNames(projectcss.all, sty.svg__wKxR2)}
                    role={"img"}
                  />
                </div>
              </div>
            </Stack__>
            <Stack__
              as={"div"}
              data-plasmic-name={"row2"}
              data-plasmic-override={overrides.row2}
              hasGap={true}
              className={classNames(projectcss.all, sty.row2)}
            >
              <div
                data-plasmic-name={"facility10"}
                data-plasmic-override={overrides.facility10}
                className={classNames(projectcss.all, sty.facility10)}
              >
                <div
                  data-plasmic-name={"rectangle12"}
                  data-plasmic-override={overrides.rectangle12}
                  className={classNames(projectcss.all, sty.rectangle12)}
                />

                <div
                  data-plasmic-name={"group13"}
                  data-plasmic-override={overrides.group13}
                  className={classNames(projectcss.all, sty.group13)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___9Yc4R
                    )}
                  >
                    {"Game center"}
                  </div>
                  <Vector10Icon
                    className={classNames(projectcss.all, sty.svg__eIaTi)}
                    role={"img"}
                  />
                </div>
              </div>
              <div
                data-plasmic-name={"facility11"}
                data-plasmic-override={overrides.facility11}
                className={classNames(projectcss.all, sty.facility11)}
              >
                <div
                  data-plasmic-name={"rectangle13"}
                  data-plasmic-override={overrides.rectangle13}
                  className={classNames(projectcss.all, sty.rectangle13)}
                />

                <div
                  data-plasmic-name={"group14"}
                  data-plasmic-override={overrides.group14}
                  className={classNames(projectcss.all, sty.group14)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__bIhZ6
                    )}
                  >
                    {"24/7 Light"}
                  </div>
                  <Vector11Icon
                    className={classNames(projectcss.all, sty.svg__ndsp1)}
                    role={"img"}
                  />
                </div>
              </div>
              <div
                data-plasmic-name={"facility12"}
                data-plasmic-override={overrides.facility12}
                className={classNames(projectcss.all, sty.facility12)}
              >
                <div
                  data-plasmic-name={"rectangle14"}
                  data-plasmic-override={overrides.rectangle14}
                  className={classNames(projectcss.all, sty.rectangle14)}
                />

                <div
                  data-plasmic-name={"group15"}
                  data-plasmic-override={overrides.group15}
                  className={classNames(projectcss.all, sty.group15)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__p1Big
                    )}
                  >
                    {"Laundry"}
                  </div>
                  <Vector12Icon
                    className={classNames(projectcss.all, sty.svg__dJbtU)}
                    role={"img"}
                  />
                </div>
              </div>
              <div
                data-plasmic-name={"facility13"}
                data-plasmic-override={overrides.facility13}
                className={classNames(projectcss.all, sty.facility13)}
              >
                <div
                  data-plasmic-name={"rectangle15"}
                  data-plasmic-override={overrides.rectangle15}
                  className={classNames(projectcss.all, sty.rectangle15)}
                />

                <div
                  data-plasmic-name={"group16"}
                  data-plasmic-override={overrides.group16}
                  className={classNames(projectcss.all, sty.group16)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__tqBtF
                    )}
                  >
                    {"Parking space"}
                  </div>
                  <Vector13Icon
                    className={classNames(projectcss.all, sty.svg__stbJ)}
                    role={"img"}
                  />
                </div>
              </div>
            </Stack__>
          </Stack__>
          <Stack__
            as={"div"}
            data-plasmic-name={"viewRooms"}
            data-plasmic-override={overrides.viewRooms}
            hasGap={true}
            className={classNames(projectcss.all, sty.viewRooms)}
          >
            <Stack__
              as={"div"}
              data-plasmic-name={"title"}
              data-plasmic-override={overrides.title}
              hasGap={true}
              className={classNames(projectcss.all, sty.title)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__b5Bd
                )}
              >
                {"Luxurious Rooms"}
              </div>
              <div
                data-plasmic-name={"rectangle16"}
                data-plasmic-override={overrides.rectangle16}
                className={classNames(projectcss.all, sty.rectangle16)}
              />

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__wUqOh
                )}
              >
                {"All room are design for your comfort"}
              </div>
            </Stack__>
            <Stack__
              as={"div"}
              data-plasmic-name={"roomsType"}
              data-plasmic-override={overrides.roomsType}
              hasGap={true}
              className={classNames(projectcss.all, sty.roomsType)}
            >
              <Stack__
                as={"div"}
                data-plasmic-name={"room1"}
                data-plasmic-override={overrides.room1}
                hasGap={true}
                className={classNames(projectcss.all, sty.room1)}
              >
                <div
                  data-plasmic-name={"rectangle17"}
                  data-plasmic-override={overrides.rectangle17}
                  className={classNames(projectcss.all, sty.rectangle17)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__xCrrw
                  )}
                >
                  {"Television set, Extra sheets and Breakfast"}
                </div>
              </Stack__>
              <Stack__
                as={"div"}
                data-plasmic-name={"room2"}
                data-plasmic-override={overrides.room2}
                hasGap={true}
                className={classNames(projectcss.all, sty.room2)}
              >
                <div
                  data-plasmic-name={"rectangle18"}
                  data-plasmic-override={overrides.rectangle18}
                  className={classNames(projectcss.all, sty.rectangle18)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__yXrlC
                  )}
                >
                  {"Television set, Breakfast, and \nfireplace"}
                </div>
              </Stack__>
              <Stack__
                as={"div"}
                data-plasmic-name={"room4"}
                data-plasmic-override={overrides.room4}
                hasGap={true}
                className={classNames(projectcss.all, sty.room4)}
              >
                <div
                  data-plasmic-name={"rectangle19"}
                  data-plasmic-override={overrides.rectangle19}
                  className={classNames(projectcss.all, sty.rectangle19)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__xSoz1
                  )}
                >
                  {
                    "Television set, ExtBreakfast, and \nfireplace, Console and bed rest"
                  }
                </div>
              </Stack__>
            </Stack__>
          </Stack__>
          <Stack__
            as={"div"}
            data-plasmic-name={"frame27"}
            data-plasmic-override={overrides.frame27}
            hasGap={true}
            className={classNames(projectcss.all, sty.frame27)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__yg05
              )}
            >
              {"Testimonies"}
            </div>
            <div
              data-plasmic-name={"frame4"}
              data-plasmic-override={overrides.frame4}
              className={classNames(projectcss.all, sty.frame4)}
            >
              <Stack__
                as={"div"}
                data-plasmic-name={"testimony1"}
                data-plasmic-override={overrides.testimony1}
                hasGap={true}
                className={classNames(projectcss.all, sty.testimony1)}
              >
                <Stack__
                  as={"div"}
                  data-plasmic-name={"frame282"}
                  data-plasmic-override={overrides.frame282}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame282)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__pgKnq
                    )}
                  >
                    {"2 Mar. 2023"}
                  </div>
                  <div
                    data-plasmic-name={"rating"}
                    data-plasmic-override={overrides.rating}
                    className={classNames(projectcss.all, sty.rating)}
                  >
                    {false ? (
                      <div
                        data-plasmic-name={"rectangle20"}
                        data-plasmic-override={overrides.rectangle20}
                        className={classNames(projectcss.all, sty.rectangle20)}
                      />
                    ) : null}
                    <Group10Icon
                      className={classNames(projectcss.all, sty.svg__mszwp)}
                      role={"img"}
                    />
                  </div>
                </Stack__>
                <div
                  data-plasmic-name={"frame283"}
                  data-plasmic-override={overrides.frame283}
                  className={classNames(projectcss.all, sty.frame283)}
                >
                  <Vector15Icon
                    className={classNames(projectcss.all, sty.svg__ssysh)}
                    role={"img"}
                  />

                  <div
                    data-plasmic-name={
                      "theServiceAtTheHotelMonteleoneWasExceptionalThereWasAbsolutelyNoIssueThatWasNotAddressedTimelyAndWithSatisfactoryResultsWeWereParticularyImpressedWithHowTheHotelStaffAnticipatedOurNeedsPeriodicallyComingByTheBoardRoomToCheckWithUsNumerousConferenceAttendeesCommentedOnTheQualityOfTheFoodTheQualityOfTheServiceAndOverallPositiveAttitudeTowardTheConferenceSiteParticularNoteworthyIsTheLongevityOfTheStaffAndThatSenseOfInvestmentInTheSuccessOfEveryEventIUsuallyOfferSuggestionsForImprovementsPartOfBeingAMarketingProfessorButThereIsAbsolutelyNothingThatCouldBeImprovedYouHaveSetTheBarVeryHigh"
                    }
                    data-plasmic-override={
                      overrides.theServiceAtTheHotelMonteleoneWasExceptionalThereWasAbsolutelyNoIssueThatWasNotAddressedTimelyAndWithSatisfactoryResultsWeWereParticularyImpressedWithHowTheHotelStaffAnticipatedOurNeedsPeriodicallyComingByTheBoardRoomToCheckWithUsNumerousConferenceAttendeesCommentedOnTheQualityOfTheFoodTheQualityOfTheServiceAndOverallPositiveAttitudeTowardTheConferenceSiteParticularNoteworthyIsTheLongevityOfTheStaffAndThatSenseOfInvestmentInTheSuccessOfEveryEventIUsuallyOfferSuggestionsForImprovementsPartOfBeingAMarketingProfessorButThereIsAbsolutelyNothingThatCouldBeImprovedYouHaveSetTheBarVeryHigh
                    }
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.theServiceAtTheHotelMonteleoneWasExceptionalThereWasAbsolutelyNoIssueThatWasNotAddressedTimelyAndWithSatisfactoryResultsWeWereParticularyImpressedWithHowTheHotelStaffAnticipatedOurNeedsPeriodicallyComingByTheBoardRoomToCheckWithUsNumerousConferenceAttendeesCommentedOnTheQualityOfTheFoodTheQualityOfTheServiceAndOverallPositiveAttitudeTowardTheConferenceSiteParticularNoteworthyIsTheLongevityOfTheStaffAndThatSenseOfInvestmentInTheSuccessOfEveryEventIUsuallyOfferSuggestionsForImprovementsPartOfBeingAMarketingProfessorButThereIsAbsolutelyNothingThatCouldBeImprovedYouHaveSetTheBarVeryHigh
                    )}
                  >
                    {
                      '    Staying on the Kivu Queen was like a dream! The combination of a luxury hotel experience and breathtaking views from the lake made it truly unforgettable. The staff went above and beyond to ensure every moment was perfect.".'
                    }
                  </div>
                  <Vector14Icon
                    className={classNames(projectcss.all, sty.svg__jzrO7)}
                    role={"img"}
                  />
                </div>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"frame284"}
                  data-plasmic-override={overrides.frame284}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame284)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__szXaK)}
                    displayHeight={"42px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"42px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/cruise_crew_iq/images/ellipse6.svg",
                      fullWidth: 42,
                      fullHeight: 42,
                      aspectRatio: 1
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lDo78
                    )}
                  >
                    {"Anna Brand"}
                  </div>
                </Stack__>
              </Stack__>
              <Stack__
                as={"div"}
                data-plasmic-name={"testimony4"}
                data-plasmic-override={overrides.testimony4}
                hasGap={true}
                className={classNames(projectcss.all, sty.testimony4)}
              >
                <Stack__
                  as={"div"}
                  data-plasmic-name={"frame285"}
                  data-plasmic-override={overrides.frame285}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame285)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zGydv
                    )}
                  >
                    {"2 Mar. 2023"}
                  </div>
                  <div
                    data-plasmic-name={"rating2"}
                    data-plasmic-override={overrides.rating2}
                    className={classNames(projectcss.all, sty.rating2)}
                  >
                    {false ? (
                      <div
                        data-plasmic-name={"rectangle21"}
                        data-plasmic-override={overrides.rectangle21}
                        className={classNames(projectcss.all, sty.rectangle21)}
                      />
                    ) : null}
                    <Group10Icon
                      className={classNames(projectcss.all, sty.svg__mn4To)}
                      role={"img"}
                    />
                  </div>
                </Stack__>
                <div
                  data-plasmic-name={"frame286"}
                  data-plasmic-override={overrides.frame286}
                  className={classNames(projectcss.all, sty.frame286)}
                >
                  <Vector15Icon
                    className={classNames(projectcss.all, sty.svg__uLpGa)}
                    role={"img"}
                  />

                  <div
                    data-plasmic-name={
                      "theServiceAtTheHotelMonteleoneWasExceptionalThereWasAbsolutelyNoIssueThatWasNotAddressedTimelyAndWithSatisfactoryResultsWeWereParticularyImpressedWithHowTheHotelStaffAnticipatedOurNeedsPeriodicallyComingByTheBoardRoomToCheckWithUsNumerousConferenceAttendeesCommentedOnTheQualityOfTheFoodTheQualityOfTheServiceAndOverallPositiveAttitudeTowardTheConferenceSiteParticularNoteworthyIsTheLongevityOfTheStaffAndThatSenseOfInvestmentInTheSuccessOfEveryEventIUsuallyOfferSuggestionsForImprovementsPartOfBeingAMarketingProfessorButThereIsAbsolutelyNothingThatCouldBeImprovedYouHaveSetTheBarVeryHigh2"
                    }
                    data-plasmic-override={
                      overrides.theServiceAtTheHotelMonteleoneWasExceptionalThereWasAbsolutelyNoIssueThatWasNotAddressedTimelyAndWithSatisfactoryResultsWeWereParticularyImpressedWithHowTheHotelStaffAnticipatedOurNeedsPeriodicallyComingByTheBoardRoomToCheckWithUsNumerousConferenceAttendeesCommentedOnTheQualityOfTheFoodTheQualityOfTheServiceAndOverallPositiveAttitudeTowardTheConferenceSiteParticularNoteworthyIsTheLongevityOfTheStaffAndThatSenseOfInvestmentInTheSuccessOfEveryEventIUsuallyOfferSuggestionsForImprovementsPartOfBeingAMarketingProfessorButThereIsAbsolutelyNothingThatCouldBeImprovedYouHaveSetTheBarVeryHigh2
                    }
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.theServiceAtTheHotelMonteleoneWasExceptionalThereWasAbsolutelyNoIssueThatWasNotAddressedTimelyAndWithSatisfactoryResultsWeWereParticularyImpressedWithHowTheHotelStaffAnticipatedOurNeedsPeriodicallyComingByTheBoardRoomToCheckWithUsNumerousConferenceAttendeesCommentedOnTheQualityOfTheFoodTheQualityOfTheServiceAndOverallPositiveAttitudeTowardTheConferenceSiteParticularNoteworthyIsTheLongevityOfTheStaffAndThatSenseOfInvestmentInTheSuccessOfEveryEventIUsuallyOfferSuggestionsForImprovementsPartOfBeingAMarketingProfessorButThereIsAbsolutelyNothingThatCouldBeImprovedYouHaveSetTheBarVeryHigh2
                    )}
                  >
                    {
                      "        From the cozy, well-appointed rooms to the excellent dining options, everything on the Kivu Queen was top-notch. The crew\u2019s warmth and attentiveness made it feel like a home on the water, with stunning scenery at every turn."
                    }
                  </div>
                  <Vector14Icon
                    className={classNames(projectcss.all, sty.svg___6Q7H)}
                    role={"img"}
                  />
                </div>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"frame287"}
                  data-plasmic-override={overrides.frame287}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame287)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__yZh1R)}
                    displayHeight={"42px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"42px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/cruise_crew_iq/images/ellipse12.svg",
                      fullWidth: 42,
                      fullHeight: 42,
                      aspectRatio: 1
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__fdHf
                    )}
                  >
                    {"Anthony Bruff"}
                  </div>
                </Stack__>
              </Stack__>
              <Stack__
                as={"div"}
                data-plasmic-name={"testimony5"}
                data-plasmic-override={overrides.testimony5}
                hasGap={true}
                className={classNames(projectcss.all, sty.testimony5)}
              >
                <Stack__
                  as={"div"}
                  data-plasmic-name={"frame288"}
                  data-plasmic-override={overrides.frame288}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame288)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qjTm
                    )}
                  >
                    {"2 Mar. 2023"}
                  </div>
                  <div
                    data-plasmic-name={"rating3"}
                    data-plasmic-override={overrides.rating3}
                    className={classNames(projectcss.all, sty.rating3)}
                  >
                    {false ? (
                      <div
                        data-plasmic-name={"rectangle22"}
                        data-plasmic-override={overrides.rectangle22}
                        className={classNames(projectcss.all, sty.rectangle22)}
                      />
                    ) : null}
                    <Group10Icon
                      className={classNames(projectcss.all, sty.svg__uwPoT)}
                      role={"img"}
                    />
                  </div>
                </Stack__>
                <div
                  data-plasmic-name={"frame289"}
                  data-plasmic-override={overrides.frame289}
                  className={classNames(projectcss.all, sty.frame289)}
                >
                  <Vector15Icon
                    className={classNames(projectcss.all, sty.svg__vsawy)}
                    role={"img"}
                  />

                  <div
                    data-plasmic-name={
                      "theServiceAtTheHotelMonteleoneWasExceptionalThereWasAbsolutelyNoIssueThatWasNotAddressedTimelyAndWithSatisfactoryResultsWeWereParticularyImpressedWithHowTheHotelStaffAnticipatedOurNeedsPeriodicallyComingByTheBoardRoomToCheckWithUsNumerousConferenceAttendeesCommentedOnTheQualityOfTheFoodTheQualityOfTheServiceAndOverallPositiveAttitudeTowardTheConferenceSiteParticularNoteworthyIsTheLongevityOfTheStaffAndThatSenseOfInvestmentInTheSuccessOfEveryEventIUsuallyOfferSuggestionsForImprovementsPartOfBeingAMarketingProfessorButThereIsAbsolutelyNothingThatCouldBeImprovedYouHaveSetTheBarVeryHigh3"
                    }
                    data-plasmic-override={
                      overrides.theServiceAtTheHotelMonteleoneWasExceptionalThereWasAbsolutelyNoIssueThatWasNotAddressedTimelyAndWithSatisfactoryResultsWeWereParticularyImpressedWithHowTheHotelStaffAnticipatedOurNeedsPeriodicallyComingByTheBoardRoomToCheckWithUsNumerousConferenceAttendeesCommentedOnTheQualityOfTheFoodTheQualityOfTheServiceAndOverallPositiveAttitudeTowardTheConferenceSiteParticularNoteworthyIsTheLongevityOfTheStaffAndThatSenseOfInvestmentInTheSuccessOfEveryEventIUsuallyOfferSuggestionsForImprovementsPartOfBeingAMarketingProfessorButThereIsAbsolutelyNothingThatCouldBeImprovedYouHaveSetTheBarVeryHigh3
                    }
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.theServiceAtTheHotelMonteleoneWasExceptionalThereWasAbsolutelyNoIssueThatWasNotAddressedTimelyAndWithSatisfactoryResultsWeWereParticularyImpressedWithHowTheHotelStaffAnticipatedOurNeedsPeriodicallyComingByTheBoardRoomToCheckWithUsNumerousConferenceAttendeesCommentedOnTheQualityOfTheFoodTheQualityOfTheServiceAndOverallPositiveAttitudeTowardTheConferenceSiteParticularNoteworthyIsTheLongevityOfTheStaffAndThatSenseOfInvestmentInTheSuccessOfEveryEventIUsuallyOfferSuggestionsForImprovementsPartOfBeingAMarketingProfessorButThereIsAbsolutelyNothingThatCouldBeImprovedYouHaveSetTheBarVeryHigh3
                    )}
                  >
                    {
                      "      The Kivu Queen exceeded all our expectations. The staff anticipated our needs with exceptional attention to detail, creating a seamless experience that felt both intimate and luxurious. This is hospitality at its finest!"
                    }
                  </div>
                  <Vector14Icon
                    className={classNames(projectcss.all, sty.svg__h2Y26)}
                    role={"img"}
                  />
                </div>
                <Stack__
                  as={"div"}
                  data-plasmic-name={"frame290"}
                  data-plasmic-override={overrides.frame290}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.frame290)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__l3XLh)}
                    displayHeight={"42px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"42px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/cruise_crew_iq/images/ellipse7.svg",
                      fullWidth: 42,
                      fullHeight: 42,
                      aspectRatio: 1
                    }}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gmFhE
                    )}
                  >
                    {"Patrick Stuff"}
                  </div>
                </Stack__>
              </Stack__>
            </div>
          </Stack__>
          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  home: [
    "home",
    "navbar",
    "group24",
    "frame30",
    "frame29",
    "group29",
    "bookBtn",
    "rectangle5",
    "frame25",
    "frame281",
    "row1",
    "facility1",
    "rectangle8",
    "group9",
    "facility7",
    "rectangle9",
    "group10",
    "facility8",
    "rectangle10",
    "group11",
    "facility9",
    "rectangle11",
    "group12",
    "row2",
    "facility10",
    "rectangle12",
    "group13",
    "facility11",
    "rectangle13",
    "group14",
    "facility12",
    "rectangle14",
    "group15",
    "facility13",
    "rectangle15",
    "group16",
    "viewRooms",
    "title",
    "rectangle16",
    "roomsType",
    "room1",
    "rectangle17",
    "room2",
    "rectangle18",
    "room4",
    "rectangle19",
    "frame27",
    "frame4",
    "testimony1",
    "frame282",
    "rating",
    "rectangle20",
    "frame283",
    "theServiceAtTheHotelMonteleoneWasExceptionalThereWasAbsolutelyNoIssueThatWasNotAddressedTimelyAndWithSatisfactoryResultsWeWereParticularyImpressedWithHowTheHotelStaffAnticipatedOurNeedsPeriodicallyComingByTheBoardRoomToCheckWithUsNumerousConferenceAttendeesCommentedOnTheQualityOfTheFoodTheQualityOfTheServiceAndOverallPositiveAttitudeTowardTheConferenceSiteParticularNoteworthyIsTheLongevityOfTheStaffAndThatSenseOfInvestmentInTheSuccessOfEveryEventIUsuallyOfferSuggestionsForImprovementsPartOfBeingAMarketingProfessorButThereIsAbsolutelyNothingThatCouldBeImprovedYouHaveSetTheBarVeryHigh",
    "frame284",
    "testimony4",
    "frame285",
    "rating2",
    "rectangle21",
    "frame286",
    "theServiceAtTheHotelMonteleoneWasExceptionalThereWasAbsolutelyNoIssueThatWasNotAddressedTimelyAndWithSatisfactoryResultsWeWereParticularyImpressedWithHowTheHotelStaffAnticipatedOurNeedsPeriodicallyComingByTheBoardRoomToCheckWithUsNumerousConferenceAttendeesCommentedOnTheQualityOfTheFoodTheQualityOfTheServiceAndOverallPositiveAttitudeTowardTheConferenceSiteParticularNoteworthyIsTheLongevityOfTheStaffAndThatSenseOfInvestmentInTheSuccessOfEveryEventIUsuallyOfferSuggestionsForImprovementsPartOfBeingAMarketingProfessorButThereIsAbsolutelyNothingThatCouldBeImprovedYouHaveSetTheBarVeryHigh2",
    "frame287",
    "testimony5",
    "frame288",
    "rating3",
    "rectangle22",
    "frame289",
    "theServiceAtTheHotelMonteleoneWasExceptionalThereWasAbsolutelyNoIssueThatWasNotAddressedTimelyAndWithSatisfactoryResultsWeWereParticularyImpressedWithHowTheHotelStaffAnticipatedOurNeedsPeriodicallyComingByTheBoardRoomToCheckWithUsNumerousConferenceAttendeesCommentedOnTheQualityOfTheFoodTheQualityOfTheServiceAndOverallPositiveAttitudeTowardTheConferenceSiteParticularNoteworthyIsTheLongevityOfTheStaffAndThatSenseOfInvestmentInTheSuccessOfEveryEventIUsuallyOfferSuggestionsForImprovementsPartOfBeingAMarketingProfessorButThereIsAbsolutelyNothingThatCouldBeImprovedYouHaveSetTheBarVeryHigh3",
    "frame290",
    "footer"
  ],
  navbar: ["navbar"],
  group24: [
    "group24",
    "frame30",
    "frame29",
    "group29",
    "bookBtn",
    "rectangle5"
  ],
  frame30: ["frame30", "frame29", "group29", "bookBtn"],
  frame29: ["frame29"],
  group29: ["group29", "bookBtn"],
  bookBtn: ["bookBtn"],
  rectangle5: ["rectangle5"],
  frame25: [
    "frame25",
    "frame281",
    "row1",
    "facility1",
    "rectangle8",
    "group9",
    "facility7",
    "rectangle9",
    "group10",
    "facility8",
    "rectangle10",
    "group11",
    "facility9",
    "rectangle11",
    "group12",
    "row2",
    "facility10",
    "rectangle12",
    "group13",
    "facility11",
    "rectangle13",
    "group14",
    "facility12",
    "rectangle14",
    "group15",
    "facility13",
    "rectangle15",
    "group16"
  ],
  frame281: ["frame281"],
  row1: [
    "row1",
    "facility1",
    "rectangle8",
    "group9",
    "facility7",
    "rectangle9",
    "group10",
    "facility8",
    "rectangle10",
    "group11",
    "facility9",
    "rectangle11",
    "group12"
  ],
  facility1: ["facility1", "rectangle8", "group9"],
  rectangle8: ["rectangle8"],
  group9: ["group9"],
  facility7: ["facility7", "rectangle9", "group10"],
  rectangle9: ["rectangle9"],
  group10: ["group10"],
  facility8: ["facility8", "rectangle10", "group11"],
  rectangle10: ["rectangle10"],
  group11: ["group11"],
  facility9: ["facility9", "rectangle11", "group12"],
  rectangle11: ["rectangle11"],
  group12: ["group12"],
  row2: [
    "row2",
    "facility10",
    "rectangle12",
    "group13",
    "facility11",
    "rectangle13",
    "group14",
    "facility12",
    "rectangle14",
    "group15",
    "facility13",
    "rectangle15",
    "group16"
  ],
  facility10: ["facility10", "rectangle12", "group13"],
  rectangle12: ["rectangle12"],
  group13: ["group13"],
  facility11: ["facility11", "rectangle13", "group14"],
  rectangle13: ["rectangle13"],
  group14: ["group14"],
  facility12: ["facility12", "rectangle14", "group15"],
  rectangle14: ["rectangle14"],
  group15: ["group15"],
  facility13: ["facility13", "rectangle15", "group16"],
  rectangle15: ["rectangle15"],
  group16: ["group16"],
  viewRooms: [
    "viewRooms",
    "title",
    "rectangle16",
    "roomsType",
    "room1",
    "rectangle17",
    "room2",
    "rectangle18",
    "room4",
    "rectangle19"
  ],
  title: ["title", "rectangle16"],
  rectangle16: ["rectangle16"],
  roomsType: [
    "roomsType",
    "room1",
    "rectangle17",
    "room2",
    "rectangle18",
    "room4",
    "rectangle19"
  ],
  room1: ["room1", "rectangle17"],
  rectangle17: ["rectangle17"],
  room2: ["room2", "rectangle18"],
  rectangle18: ["rectangle18"],
  room4: ["room4", "rectangle19"],
  rectangle19: ["rectangle19"],
  frame27: [
    "frame27",
    "frame4",
    "testimony1",
    "frame282",
    "rating",
    "rectangle20",
    "frame283",
    "theServiceAtTheHotelMonteleoneWasExceptionalThereWasAbsolutelyNoIssueThatWasNotAddressedTimelyAndWithSatisfactoryResultsWeWereParticularyImpressedWithHowTheHotelStaffAnticipatedOurNeedsPeriodicallyComingByTheBoardRoomToCheckWithUsNumerousConferenceAttendeesCommentedOnTheQualityOfTheFoodTheQualityOfTheServiceAndOverallPositiveAttitudeTowardTheConferenceSiteParticularNoteworthyIsTheLongevityOfTheStaffAndThatSenseOfInvestmentInTheSuccessOfEveryEventIUsuallyOfferSuggestionsForImprovementsPartOfBeingAMarketingProfessorButThereIsAbsolutelyNothingThatCouldBeImprovedYouHaveSetTheBarVeryHigh",
    "frame284",
    "testimony4",
    "frame285",
    "rating2",
    "rectangle21",
    "frame286",
    "theServiceAtTheHotelMonteleoneWasExceptionalThereWasAbsolutelyNoIssueThatWasNotAddressedTimelyAndWithSatisfactoryResultsWeWereParticularyImpressedWithHowTheHotelStaffAnticipatedOurNeedsPeriodicallyComingByTheBoardRoomToCheckWithUsNumerousConferenceAttendeesCommentedOnTheQualityOfTheFoodTheQualityOfTheServiceAndOverallPositiveAttitudeTowardTheConferenceSiteParticularNoteworthyIsTheLongevityOfTheStaffAndThatSenseOfInvestmentInTheSuccessOfEveryEventIUsuallyOfferSuggestionsForImprovementsPartOfBeingAMarketingProfessorButThereIsAbsolutelyNothingThatCouldBeImprovedYouHaveSetTheBarVeryHigh2",
    "frame287",
    "testimony5",
    "frame288",
    "rating3",
    "rectangle22",
    "frame289",
    "theServiceAtTheHotelMonteleoneWasExceptionalThereWasAbsolutelyNoIssueThatWasNotAddressedTimelyAndWithSatisfactoryResultsWeWereParticularyImpressedWithHowTheHotelStaffAnticipatedOurNeedsPeriodicallyComingByTheBoardRoomToCheckWithUsNumerousConferenceAttendeesCommentedOnTheQualityOfTheFoodTheQualityOfTheServiceAndOverallPositiveAttitudeTowardTheConferenceSiteParticularNoteworthyIsTheLongevityOfTheStaffAndThatSenseOfInvestmentInTheSuccessOfEveryEventIUsuallyOfferSuggestionsForImprovementsPartOfBeingAMarketingProfessorButThereIsAbsolutelyNothingThatCouldBeImprovedYouHaveSetTheBarVeryHigh3",
    "frame290"
  ],
  frame4: [
    "frame4",
    "testimony1",
    "frame282",
    "rating",
    "rectangle20",
    "frame283",
    "theServiceAtTheHotelMonteleoneWasExceptionalThereWasAbsolutelyNoIssueThatWasNotAddressedTimelyAndWithSatisfactoryResultsWeWereParticularyImpressedWithHowTheHotelStaffAnticipatedOurNeedsPeriodicallyComingByTheBoardRoomToCheckWithUsNumerousConferenceAttendeesCommentedOnTheQualityOfTheFoodTheQualityOfTheServiceAndOverallPositiveAttitudeTowardTheConferenceSiteParticularNoteworthyIsTheLongevityOfTheStaffAndThatSenseOfInvestmentInTheSuccessOfEveryEventIUsuallyOfferSuggestionsForImprovementsPartOfBeingAMarketingProfessorButThereIsAbsolutelyNothingThatCouldBeImprovedYouHaveSetTheBarVeryHigh",
    "frame284",
    "testimony4",
    "frame285",
    "rating2",
    "rectangle21",
    "frame286",
    "theServiceAtTheHotelMonteleoneWasExceptionalThereWasAbsolutelyNoIssueThatWasNotAddressedTimelyAndWithSatisfactoryResultsWeWereParticularyImpressedWithHowTheHotelStaffAnticipatedOurNeedsPeriodicallyComingByTheBoardRoomToCheckWithUsNumerousConferenceAttendeesCommentedOnTheQualityOfTheFoodTheQualityOfTheServiceAndOverallPositiveAttitudeTowardTheConferenceSiteParticularNoteworthyIsTheLongevityOfTheStaffAndThatSenseOfInvestmentInTheSuccessOfEveryEventIUsuallyOfferSuggestionsForImprovementsPartOfBeingAMarketingProfessorButThereIsAbsolutelyNothingThatCouldBeImprovedYouHaveSetTheBarVeryHigh2",
    "frame287",
    "testimony5",
    "frame288",
    "rating3",
    "rectangle22",
    "frame289",
    "theServiceAtTheHotelMonteleoneWasExceptionalThereWasAbsolutelyNoIssueThatWasNotAddressedTimelyAndWithSatisfactoryResultsWeWereParticularyImpressedWithHowTheHotelStaffAnticipatedOurNeedsPeriodicallyComingByTheBoardRoomToCheckWithUsNumerousConferenceAttendeesCommentedOnTheQualityOfTheFoodTheQualityOfTheServiceAndOverallPositiveAttitudeTowardTheConferenceSiteParticularNoteworthyIsTheLongevityOfTheStaffAndThatSenseOfInvestmentInTheSuccessOfEveryEventIUsuallyOfferSuggestionsForImprovementsPartOfBeingAMarketingProfessorButThereIsAbsolutelyNothingThatCouldBeImprovedYouHaveSetTheBarVeryHigh3",
    "frame290"
  ],
  testimony1: [
    "testimony1",
    "frame282",
    "rating",
    "rectangle20",
    "frame283",
    "theServiceAtTheHotelMonteleoneWasExceptionalThereWasAbsolutelyNoIssueThatWasNotAddressedTimelyAndWithSatisfactoryResultsWeWereParticularyImpressedWithHowTheHotelStaffAnticipatedOurNeedsPeriodicallyComingByTheBoardRoomToCheckWithUsNumerousConferenceAttendeesCommentedOnTheQualityOfTheFoodTheQualityOfTheServiceAndOverallPositiveAttitudeTowardTheConferenceSiteParticularNoteworthyIsTheLongevityOfTheStaffAndThatSenseOfInvestmentInTheSuccessOfEveryEventIUsuallyOfferSuggestionsForImprovementsPartOfBeingAMarketingProfessorButThereIsAbsolutelyNothingThatCouldBeImprovedYouHaveSetTheBarVeryHigh",
    "frame284"
  ],
  frame282: ["frame282", "rating", "rectangle20"],
  rating: ["rating", "rectangle20"],
  rectangle20: ["rectangle20"],
  frame283: [
    "frame283",
    "theServiceAtTheHotelMonteleoneWasExceptionalThereWasAbsolutelyNoIssueThatWasNotAddressedTimelyAndWithSatisfactoryResultsWeWereParticularyImpressedWithHowTheHotelStaffAnticipatedOurNeedsPeriodicallyComingByTheBoardRoomToCheckWithUsNumerousConferenceAttendeesCommentedOnTheQualityOfTheFoodTheQualityOfTheServiceAndOverallPositiveAttitudeTowardTheConferenceSiteParticularNoteworthyIsTheLongevityOfTheStaffAndThatSenseOfInvestmentInTheSuccessOfEveryEventIUsuallyOfferSuggestionsForImprovementsPartOfBeingAMarketingProfessorButThereIsAbsolutelyNothingThatCouldBeImprovedYouHaveSetTheBarVeryHigh"
  ],
  theServiceAtTheHotelMonteleoneWasExceptionalThereWasAbsolutelyNoIssueThatWasNotAddressedTimelyAndWithSatisfactoryResultsWeWereParticularyImpressedWithHowTheHotelStaffAnticipatedOurNeedsPeriodicallyComingByTheBoardRoomToCheckWithUsNumerousConferenceAttendeesCommentedOnTheQualityOfTheFoodTheQualityOfTheServiceAndOverallPositiveAttitudeTowardTheConferenceSiteParticularNoteworthyIsTheLongevityOfTheStaffAndThatSenseOfInvestmentInTheSuccessOfEveryEventIUsuallyOfferSuggestionsForImprovementsPartOfBeingAMarketingProfessorButThereIsAbsolutelyNothingThatCouldBeImprovedYouHaveSetTheBarVeryHigh:
    [
      "theServiceAtTheHotelMonteleoneWasExceptionalThereWasAbsolutelyNoIssueThatWasNotAddressedTimelyAndWithSatisfactoryResultsWeWereParticularyImpressedWithHowTheHotelStaffAnticipatedOurNeedsPeriodicallyComingByTheBoardRoomToCheckWithUsNumerousConferenceAttendeesCommentedOnTheQualityOfTheFoodTheQualityOfTheServiceAndOverallPositiveAttitudeTowardTheConferenceSiteParticularNoteworthyIsTheLongevityOfTheStaffAndThatSenseOfInvestmentInTheSuccessOfEveryEventIUsuallyOfferSuggestionsForImprovementsPartOfBeingAMarketingProfessorButThereIsAbsolutelyNothingThatCouldBeImprovedYouHaveSetTheBarVeryHigh"
    ],
  frame284: ["frame284"],
  testimony4: [
    "testimony4",
    "frame285",
    "rating2",
    "rectangle21",
    "frame286",
    "theServiceAtTheHotelMonteleoneWasExceptionalThereWasAbsolutelyNoIssueThatWasNotAddressedTimelyAndWithSatisfactoryResultsWeWereParticularyImpressedWithHowTheHotelStaffAnticipatedOurNeedsPeriodicallyComingByTheBoardRoomToCheckWithUsNumerousConferenceAttendeesCommentedOnTheQualityOfTheFoodTheQualityOfTheServiceAndOverallPositiveAttitudeTowardTheConferenceSiteParticularNoteworthyIsTheLongevityOfTheStaffAndThatSenseOfInvestmentInTheSuccessOfEveryEventIUsuallyOfferSuggestionsForImprovementsPartOfBeingAMarketingProfessorButThereIsAbsolutelyNothingThatCouldBeImprovedYouHaveSetTheBarVeryHigh2",
    "frame287"
  ],
  frame285: ["frame285", "rating2", "rectangle21"],
  rating2: ["rating2", "rectangle21"],
  rectangle21: ["rectangle21"],
  frame286: [
    "frame286",
    "theServiceAtTheHotelMonteleoneWasExceptionalThereWasAbsolutelyNoIssueThatWasNotAddressedTimelyAndWithSatisfactoryResultsWeWereParticularyImpressedWithHowTheHotelStaffAnticipatedOurNeedsPeriodicallyComingByTheBoardRoomToCheckWithUsNumerousConferenceAttendeesCommentedOnTheQualityOfTheFoodTheQualityOfTheServiceAndOverallPositiveAttitudeTowardTheConferenceSiteParticularNoteworthyIsTheLongevityOfTheStaffAndThatSenseOfInvestmentInTheSuccessOfEveryEventIUsuallyOfferSuggestionsForImprovementsPartOfBeingAMarketingProfessorButThereIsAbsolutelyNothingThatCouldBeImprovedYouHaveSetTheBarVeryHigh2"
  ],
  theServiceAtTheHotelMonteleoneWasExceptionalThereWasAbsolutelyNoIssueThatWasNotAddressedTimelyAndWithSatisfactoryResultsWeWereParticularyImpressedWithHowTheHotelStaffAnticipatedOurNeedsPeriodicallyComingByTheBoardRoomToCheckWithUsNumerousConferenceAttendeesCommentedOnTheQualityOfTheFoodTheQualityOfTheServiceAndOverallPositiveAttitudeTowardTheConferenceSiteParticularNoteworthyIsTheLongevityOfTheStaffAndThatSenseOfInvestmentInTheSuccessOfEveryEventIUsuallyOfferSuggestionsForImprovementsPartOfBeingAMarketingProfessorButThereIsAbsolutelyNothingThatCouldBeImprovedYouHaveSetTheBarVeryHigh2:
    [
      "theServiceAtTheHotelMonteleoneWasExceptionalThereWasAbsolutelyNoIssueThatWasNotAddressedTimelyAndWithSatisfactoryResultsWeWereParticularyImpressedWithHowTheHotelStaffAnticipatedOurNeedsPeriodicallyComingByTheBoardRoomToCheckWithUsNumerousConferenceAttendeesCommentedOnTheQualityOfTheFoodTheQualityOfTheServiceAndOverallPositiveAttitudeTowardTheConferenceSiteParticularNoteworthyIsTheLongevityOfTheStaffAndThatSenseOfInvestmentInTheSuccessOfEveryEventIUsuallyOfferSuggestionsForImprovementsPartOfBeingAMarketingProfessorButThereIsAbsolutelyNothingThatCouldBeImprovedYouHaveSetTheBarVeryHigh2"
    ],
  frame287: ["frame287"],
  testimony5: [
    "testimony5",
    "frame288",
    "rating3",
    "rectangle22",
    "frame289",
    "theServiceAtTheHotelMonteleoneWasExceptionalThereWasAbsolutelyNoIssueThatWasNotAddressedTimelyAndWithSatisfactoryResultsWeWereParticularyImpressedWithHowTheHotelStaffAnticipatedOurNeedsPeriodicallyComingByTheBoardRoomToCheckWithUsNumerousConferenceAttendeesCommentedOnTheQualityOfTheFoodTheQualityOfTheServiceAndOverallPositiveAttitudeTowardTheConferenceSiteParticularNoteworthyIsTheLongevityOfTheStaffAndThatSenseOfInvestmentInTheSuccessOfEveryEventIUsuallyOfferSuggestionsForImprovementsPartOfBeingAMarketingProfessorButThereIsAbsolutelyNothingThatCouldBeImprovedYouHaveSetTheBarVeryHigh3",
    "frame290"
  ],
  frame288: ["frame288", "rating3", "rectangle22"],
  rating3: ["rating3", "rectangle22"],
  rectangle22: ["rectangle22"],
  frame289: [
    "frame289",
    "theServiceAtTheHotelMonteleoneWasExceptionalThereWasAbsolutelyNoIssueThatWasNotAddressedTimelyAndWithSatisfactoryResultsWeWereParticularyImpressedWithHowTheHotelStaffAnticipatedOurNeedsPeriodicallyComingByTheBoardRoomToCheckWithUsNumerousConferenceAttendeesCommentedOnTheQualityOfTheFoodTheQualityOfTheServiceAndOverallPositiveAttitudeTowardTheConferenceSiteParticularNoteworthyIsTheLongevityOfTheStaffAndThatSenseOfInvestmentInTheSuccessOfEveryEventIUsuallyOfferSuggestionsForImprovementsPartOfBeingAMarketingProfessorButThereIsAbsolutelyNothingThatCouldBeImprovedYouHaveSetTheBarVeryHigh3"
  ],
  theServiceAtTheHotelMonteleoneWasExceptionalThereWasAbsolutelyNoIssueThatWasNotAddressedTimelyAndWithSatisfactoryResultsWeWereParticularyImpressedWithHowTheHotelStaffAnticipatedOurNeedsPeriodicallyComingByTheBoardRoomToCheckWithUsNumerousConferenceAttendeesCommentedOnTheQualityOfTheFoodTheQualityOfTheServiceAndOverallPositiveAttitudeTowardTheConferenceSiteParticularNoteworthyIsTheLongevityOfTheStaffAndThatSenseOfInvestmentInTheSuccessOfEveryEventIUsuallyOfferSuggestionsForImprovementsPartOfBeingAMarketingProfessorButThereIsAbsolutelyNothingThatCouldBeImprovedYouHaveSetTheBarVeryHigh3:
    [
      "theServiceAtTheHotelMonteleoneWasExceptionalThereWasAbsolutelyNoIssueThatWasNotAddressedTimelyAndWithSatisfactoryResultsWeWereParticularyImpressedWithHowTheHotelStaffAnticipatedOurNeedsPeriodicallyComingByTheBoardRoomToCheckWithUsNumerousConferenceAttendeesCommentedOnTheQualityOfTheFoodTheQualityOfTheServiceAndOverallPositiveAttitudeTowardTheConferenceSiteParticularNoteworthyIsTheLongevityOfTheStaffAndThatSenseOfInvestmentInTheSuccessOfEveryEventIUsuallyOfferSuggestionsForImprovementsPartOfBeingAMarketingProfessorButThereIsAbsolutelyNothingThatCouldBeImprovedYouHaveSetTheBarVeryHigh3"
    ],
  frame290: ["frame290"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  home: "div";
  navbar: typeof Navbar;
  group24: "div";
  frame30: "div";
  frame29: "div";
  group29: "div";
  bookBtn: "a";
  rectangle5: "div";
  frame25: "div";
  frame281: "div";
  row1: "div";
  facility1: "div";
  rectangle8: "div";
  group9: "div";
  facility7: "div";
  rectangle9: "div";
  group10: "div";
  facility8: "div";
  rectangle10: "div";
  group11: "div";
  facility9: "div";
  rectangle11: "div";
  group12: "div";
  row2: "div";
  facility10: "div";
  rectangle12: "div";
  group13: "div";
  facility11: "div";
  rectangle13: "div";
  group14: "div";
  facility12: "div";
  rectangle14: "div";
  group15: "div";
  facility13: "div";
  rectangle15: "div";
  group16: "div";
  viewRooms: "div";
  title: "div";
  rectangle16: "div";
  roomsType: "div";
  room1: "div";
  rectangle17: "div";
  room2: "div";
  rectangle18: "div";
  room4: "div";
  rectangle19: "div";
  frame27: "div";
  frame4: "div";
  testimony1: "div";
  frame282: "div";
  rating: "div";
  rectangle20: "div";
  frame283: "div";
  theServiceAtTheHotelMonteleoneWasExceptionalThereWasAbsolutelyNoIssueThatWasNotAddressedTimelyAndWithSatisfactoryResultsWeWereParticularyImpressedWithHowTheHotelStaffAnticipatedOurNeedsPeriodicallyComingByTheBoardRoomToCheckWithUsNumerousConferenceAttendeesCommentedOnTheQualityOfTheFoodTheQualityOfTheServiceAndOverallPositiveAttitudeTowardTheConferenceSiteParticularNoteworthyIsTheLongevityOfTheStaffAndThatSenseOfInvestmentInTheSuccessOfEveryEventIUsuallyOfferSuggestionsForImprovementsPartOfBeingAMarketingProfessorButThereIsAbsolutelyNothingThatCouldBeImprovedYouHaveSetTheBarVeryHigh: "div";
  frame284: "div";
  testimony4: "div";
  frame285: "div";
  rating2: "div";
  rectangle21: "div";
  frame286: "div";
  theServiceAtTheHotelMonteleoneWasExceptionalThereWasAbsolutelyNoIssueThatWasNotAddressedTimelyAndWithSatisfactoryResultsWeWereParticularyImpressedWithHowTheHotelStaffAnticipatedOurNeedsPeriodicallyComingByTheBoardRoomToCheckWithUsNumerousConferenceAttendeesCommentedOnTheQualityOfTheFoodTheQualityOfTheServiceAndOverallPositiveAttitudeTowardTheConferenceSiteParticularNoteworthyIsTheLongevityOfTheStaffAndThatSenseOfInvestmentInTheSuccessOfEveryEventIUsuallyOfferSuggestionsForImprovementsPartOfBeingAMarketingProfessorButThereIsAbsolutelyNothingThatCouldBeImprovedYouHaveSetTheBarVeryHigh2: "div";
  frame287: "div";
  testimony5: "div";
  frame288: "div";
  rating3: "div";
  rectangle22: "div";
  frame289: "div";
  theServiceAtTheHotelMonteleoneWasExceptionalThereWasAbsolutelyNoIssueThatWasNotAddressedTimelyAndWithSatisfactoryResultsWeWereParticularyImpressedWithHowTheHotelStaffAnticipatedOurNeedsPeriodicallyComingByTheBoardRoomToCheckWithUsNumerousConferenceAttendeesCommentedOnTheQualityOfTheFoodTheQualityOfTheServiceAndOverallPositiveAttitudeTowardTheConferenceSiteParticularNoteworthyIsTheLongevityOfTheStaffAndThatSenseOfInvestmentInTheSuccessOfEveryEventIUsuallyOfferSuggestionsForImprovementsPartOfBeingAMarketingProfessorButThereIsAbsolutelyNothingThatCouldBeImprovedYouHaveSetTheBarVeryHigh3: "div";
  frame290: "div";
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicHomepage__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "home") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

function withUsePlasmicAuth<P extends object>(
  WrappedComponent: React.ComponentType<P>
) {
  const WithUsePlasmicAuthComponent: React.FC<P> = props => {
    const dataSourceCtx = usePlasmicDataSourceContext() ?? {};
    const { isUserLoading, user, token } = plasmicAuth.usePlasmicAuth({
      appId: "r6SzurXsLMJXPqEBWV3sKk"
    });

    return (
      <PlasmicDataSourceContextProvider__
        value={{
          ...dataSourceCtx,
          isUserLoading,
          userAuthToken: token,
          user
        }}
      >
        <WrappedComponent {...props} />
      </PlasmicDataSourceContextProvider__>
    );
  };
  return WithUsePlasmicAuthComponent;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  withUsePlasmicAuth(makeNodeComponent("home")),
  {
    // Helper components rendering sub-elements
    navbar: makeNodeComponent("navbar"),
    group24: makeNodeComponent("group24"),
    frame30: makeNodeComponent("frame30"),
    frame29: makeNodeComponent("frame29"),
    group29: makeNodeComponent("group29"),
    bookBtn: makeNodeComponent("bookBtn"),
    rectangle5: makeNodeComponent("rectangle5"),
    frame25: makeNodeComponent("frame25"),
    frame281: makeNodeComponent("frame281"),
    row1: makeNodeComponent("row1"),
    facility1: makeNodeComponent("facility1"),
    rectangle8: makeNodeComponent("rectangle8"),
    group9: makeNodeComponent("group9"),
    facility7: makeNodeComponent("facility7"),
    rectangle9: makeNodeComponent("rectangle9"),
    group10: makeNodeComponent("group10"),
    facility8: makeNodeComponent("facility8"),
    rectangle10: makeNodeComponent("rectangle10"),
    group11: makeNodeComponent("group11"),
    facility9: makeNodeComponent("facility9"),
    rectangle11: makeNodeComponent("rectangle11"),
    group12: makeNodeComponent("group12"),
    row2: makeNodeComponent("row2"),
    facility10: makeNodeComponent("facility10"),
    rectangle12: makeNodeComponent("rectangle12"),
    group13: makeNodeComponent("group13"),
    facility11: makeNodeComponent("facility11"),
    rectangle13: makeNodeComponent("rectangle13"),
    group14: makeNodeComponent("group14"),
    facility12: makeNodeComponent("facility12"),
    rectangle14: makeNodeComponent("rectangle14"),
    group15: makeNodeComponent("group15"),
    facility13: makeNodeComponent("facility13"),
    rectangle15: makeNodeComponent("rectangle15"),
    group16: makeNodeComponent("group16"),
    viewRooms: makeNodeComponent("viewRooms"),
    title: makeNodeComponent("title"),
    rectangle16: makeNodeComponent("rectangle16"),
    roomsType: makeNodeComponent("roomsType"),
    room1: makeNodeComponent("room1"),
    rectangle17: makeNodeComponent("rectangle17"),
    room2: makeNodeComponent("room2"),
    rectangle18: makeNodeComponent("rectangle18"),
    room4: makeNodeComponent("room4"),
    rectangle19: makeNodeComponent("rectangle19"),
    frame27: makeNodeComponent("frame27"),
    frame4: makeNodeComponent("frame4"),
    testimony1: makeNodeComponent("testimony1"),
    frame282: makeNodeComponent("frame282"),
    rating: makeNodeComponent("rating"),
    rectangle20: makeNodeComponent("rectangle20"),
    frame283: makeNodeComponent("frame283"),
    theServiceAtTheHotelMonteleoneWasExceptionalThereWasAbsolutelyNoIssueThatWasNotAddressedTimelyAndWithSatisfactoryResultsWeWereParticularyImpressedWithHowTheHotelStaffAnticipatedOurNeedsPeriodicallyComingByTheBoardRoomToCheckWithUsNumerousConferenceAttendeesCommentedOnTheQualityOfTheFoodTheQualityOfTheServiceAndOverallPositiveAttitudeTowardTheConferenceSiteParticularNoteworthyIsTheLongevityOfTheStaffAndThatSenseOfInvestmentInTheSuccessOfEveryEventIUsuallyOfferSuggestionsForImprovementsPartOfBeingAMarketingProfessorButThereIsAbsolutelyNothingThatCouldBeImprovedYouHaveSetTheBarVeryHigh:
      makeNodeComponent(
        "theServiceAtTheHotelMonteleoneWasExceptionalThereWasAbsolutelyNoIssueThatWasNotAddressedTimelyAndWithSatisfactoryResultsWeWereParticularyImpressedWithHowTheHotelStaffAnticipatedOurNeedsPeriodicallyComingByTheBoardRoomToCheckWithUsNumerousConferenceAttendeesCommentedOnTheQualityOfTheFoodTheQualityOfTheServiceAndOverallPositiveAttitudeTowardTheConferenceSiteParticularNoteworthyIsTheLongevityOfTheStaffAndThatSenseOfInvestmentInTheSuccessOfEveryEventIUsuallyOfferSuggestionsForImprovementsPartOfBeingAMarketingProfessorButThereIsAbsolutelyNothingThatCouldBeImprovedYouHaveSetTheBarVeryHigh"
      ),
    frame284: makeNodeComponent("frame284"),
    testimony4: makeNodeComponent("testimony4"),
    frame285: makeNodeComponent("frame285"),
    rating2: makeNodeComponent("rating2"),
    rectangle21: makeNodeComponent("rectangle21"),
    frame286: makeNodeComponent("frame286"),
    theServiceAtTheHotelMonteleoneWasExceptionalThereWasAbsolutelyNoIssueThatWasNotAddressedTimelyAndWithSatisfactoryResultsWeWereParticularyImpressedWithHowTheHotelStaffAnticipatedOurNeedsPeriodicallyComingByTheBoardRoomToCheckWithUsNumerousConferenceAttendeesCommentedOnTheQualityOfTheFoodTheQualityOfTheServiceAndOverallPositiveAttitudeTowardTheConferenceSiteParticularNoteworthyIsTheLongevityOfTheStaffAndThatSenseOfInvestmentInTheSuccessOfEveryEventIUsuallyOfferSuggestionsForImprovementsPartOfBeingAMarketingProfessorButThereIsAbsolutelyNothingThatCouldBeImprovedYouHaveSetTheBarVeryHigh2:
      makeNodeComponent(
        "theServiceAtTheHotelMonteleoneWasExceptionalThereWasAbsolutelyNoIssueThatWasNotAddressedTimelyAndWithSatisfactoryResultsWeWereParticularyImpressedWithHowTheHotelStaffAnticipatedOurNeedsPeriodicallyComingByTheBoardRoomToCheckWithUsNumerousConferenceAttendeesCommentedOnTheQualityOfTheFoodTheQualityOfTheServiceAndOverallPositiveAttitudeTowardTheConferenceSiteParticularNoteworthyIsTheLongevityOfTheStaffAndThatSenseOfInvestmentInTheSuccessOfEveryEventIUsuallyOfferSuggestionsForImprovementsPartOfBeingAMarketingProfessorButThereIsAbsolutelyNothingThatCouldBeImprovedYouHaveSetTheBarVeryHigh2"
      ),
    frame287: makeNodeComponent("frame287"),
    testimony5: makeNodeComponent("testimony5"),
    frame288: makeNodeComponent("frame288"),
    rating3: makeNodeComponent("rating3"),
    rectangle22: makeNodeComponent("rectangle22"),
    frame289: makeNodeComponent("frame289"),
    theServiceAtTheHotelMonteleoneWasExceptionalThereWasAbsolutelyNoIssueThatWasNotAddressedTimelyAndWithSatisfactoryResultsWeWereParticularyImpressedWithHowTheHotelStaffAnticipatedOurNeedsPeriodicallyComingByTheBoardRoomToCheckWithUsNumerousConferenceAttendeesCommentedOnTheQualityOfTheFoodTheQualityOfTheServiceAndOverallPositiveAttitudeTowardTheConferenceSiteParticularNoteworthyIsTheLongevityOfTheStaffAndThatSenseOfInvestmentInTheSuccessOfEveryEventIUsuallyOfferSuggestionsForImprovementsPartOfBeingAMarketingProfessorButThereIsAbsolutelyNothingThatCouldBeImprovedYouHaveSetTheBarVeryHigh3:
      makeNodeComponent(
        "theServiceAtTheHotelMonteleoneWasExceptionalThereWasAbsolutelyNoIssueThatWasNotAddressedTimelyAndWithSatisfactoryResultsWeWereParticularyImpressedWithHowTheHotelStaffAnticipatedOurNeedsPeriodicallyComingByTheBoardRoomToCheckWithUsNumerousConferenceAttendeesCommentedOnTheQualityOfTheFoodTheQualityOfTheServiceAndOverallPositiveAttitudeTowardTheConferenceSiteParticularNoteworthyIsTheLongevityOfTheStaffAndThatSenseOfInvestmentInTheSuccessOfEveryEventIUsuallyOfferSuggestionsForImprovementsPartOfBeingAMarketingProfessorButThereIsAbsolutelyNothingThatCouldBeImprovedYouHaveSetTheBarVeryHigh3"
      ),
    frame290: makeNodeComponent("frame290"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
