// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: r6SzurXsLMJXPqEBWV3sKk
// Component: rETShnrZA2k5

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";
import * as plasmicAuth from "@plasmicapp/react-web/lib/auth";
import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";

import Navbar from "../../Navbar"; // plasmic-import: 8V9ZObcqgPEi/component
import Footer from "../../Footer"; // plasmic-import: tfXGV_GyVRZh/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: r6SzurXsLMJXPqEBWV3sKk/projectcss
import sty from "./PlasmicRooms.module.css"; // plasmic-import: rETShnrZA2k5/css

import Vector16Icon from "./icons/PlasmicIcon__Vector16"; // plasmic-import: oo59eN_ZpzYi/icon

createPlasmicElementProxy;

export type PlasmicRooms__VariantMembers = {};
export type PlasmicRooms__VariantsArgs = {};
type VariantPropType = keyof PlasmicRooms__VariantsArgs;
export const PlasmicRooms__VariantProps = new Array<VariantPropType>();

export type PlasmicRooms__ArgsType = {};
type ArgPropType = keyof PlasmicRooms__ArgsType;
export const PlasmicRooms__ArgProps = new Array<ArgPropType>();

export type PlasmicRooms__OverridesType = {
  rooms?: Flex__<"div">;
  navbar?: Flex__<typeof Navbar>;
  hero?: Flex__<"div">;
  textInfo?: Flex__<"div">;
  scrollDown?: Flex__<"div">;
  svg?: Flex__<"svg">;
  rectangle25?: Flex__<"div">;
  frame279?: Flex__<"div">;
  frame280?: Flex__<"div">;
  room1?: Flex__<"div">;
  rectangle9?: Flex__<"div">;
  rectangle26?: Flex__<"div">;
  group20?: Flex__<"div">;
  rectangle28?: Flex__<"div">;
  rectangle27?: Flex__<"div">;
  group21?: Flex__<"div">;
  room2?: Flex__<"div">;
  rectangle10?: Flex__<"div">;
  rectangle29?: Flex__<"div">;
  rectangle30?: Flex__<"div">;
  group22?: Flex__<"div">;
  rectangle31?: Flex__<"div">;
  group23?: Flex__<"div">;
  room3?: Flex__<"div">;
  rectangle11?: Flex__<"div">;
  rectangle32?: Flex__<"div">;
  rectangle33?: Flex__<"div">;
  group24?: Flex__<"div">;
  rectangle34?: Flex__<"div">;
  group25?: Flex__<"div">;
  room4?: Flex__<"div">;
  rectangle12?: Flex__<"div">;
  rectangle35?: Flex__<"div">;
  rectangle36?: Flex__<"div">;
  group26?: Flex__<"div">;
  rectangle37?: Flex__<"div">;
  group27?: Flex__<"div">;
  room5?: Flex__<"div">;
  rectangle13?: Flex__<"div">;
  rectangle38?: Flex__<"div">;
  rectangle39?: Flex__<"div">;
  group28?: Flex__<"div">;
  rectangle40?: Flex__<"div">;
  group29?: Flex__<"div">;
  room6?: Flex__<"div">;
  rectangle14?: Flex__<"div">;
  rectangle41?: Flex__<"div">;
  rectangle42?: Flex__<"div">;
  group30?: Flex__<"div">;
  rectangle43?: Flex__<"div">;
  group31?: Flex__<"div">;
  footer?: Flex__<typeof Footer>;
};

export interface DefaultRoomsProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicRooms__RenderFunc(props: {
  variants: PlasmicRooms__VariantsArgs;
  args: PlasmicRooms__ArgsType;
  overrides: PlasmicRooms__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"rooms"}
          data-plasmic-override={overrides.rooms}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.rooms
          )}
        >
          <Navbar
            data-plasmic-name={"navbar"}
            data-plasmic-override={overrides.navbar}
            className={classNames("__wab_instance", sty.navbar)}
          />

          <Stack__
            as={"div"}
            data-plasmic-name={"hero"}
            data-plasmic-override={overrides.hero}
            hasGap={true}
            className={classNames(projectcss.all, sty.hero)}
          >
            <div
              data-plasmic-name={"textInfo"}
              data-plasmic-override={overrides.textInfo}
              className={classNames(projectcss.all, sty.textInfo)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ecd3
                )}
              >
                {"Rooms and Suites"}
              </div>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__p2Rj3
                )}
              >
                {
                  "The elegant luxury bedrooms in this gallery showcase custom interior \ndesigns & decorating ideas. View pictures and find your\n perfect luxury bedroom design."
                }
              </div>
              <div
                data-plasmic-name={"scrollDown"}
                data-plasmic-override={overrides.scrollDown}
                className={classNames(projectcss.all, sty.scrollDown)}
              >
                <Vector16Icon
                  data-plasmic-name={"svg"}
                  data-plasmic-override={overrides.svg}
                  className={classNames(projectcss.all, sty.svg)}
                  role={"img"}
                />

                <div
                  data-plasmic-name={"rectangle25"}
                  data-plasmic-override={overrides.rectangle25}
                  className={classNames(projectcss.all, sty.rectangle25)}
                />
              </div>
            </div>
          </Stack__>
          <Stack__
            as={"div"}
            data-plasmic-name={"frame279"}
            data-plasmic-override={overrides.frame279}
            hasGap={true}
            className={classNames(projectcss.all, sty.frame279)}
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__tGEpQ
              )}
            >
              {"Available Rooms"}
            </div>
            <Stack__
              as={"div"}
              data-plasmic-name={"frame280"}
              data-plasmic-override={overrides.frame280}
              hasGap={true}
              className={classNames(projectcss.all, sty.frame280)}
            >
              <div
                data-plasmic-name={"room1"}
                data-plasmic-override={overrides.room1}
                className={classNames(projectcss.all, sty.room1)}
              >
                <div
                  data-plasmic-name={"rectangle9"}
                  data-plasmic-override={overrides.rectangle9}
                  className={classNames(projectcss.all, sty.rectangle9)}
                />

                <div
                  data-plasmic-name={"rectangle26"}
                  data-plasmic-override={overrides.rectangle26}
                  className={classNames(projectcss.all, sty.rectangle26)}
                />

                <div
                  data-plasmic-name={"group20"}
                  data-plasmic-override={overrides.group20}
                  className={classNames(projectcss.all, sty.group20)}
                >
                  <div
                    data-plasmic-name={"rectangle28"}
                    data-plasmic-override={overrides.rectangle28}
                    className={classNames(projectcss.all, sty.rectangle28)}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ftI3F
                    )}
                  >
                    {"Book now"}
                  </div>
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__debRw
                  )}
                >
                  {"The Royal Room"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__sJExG
                  )}
                >
                  {"\u20a6190,000"}
                </div>
                <div
                  data-plasmic-name={"rectangle27"}
                  data-plasmic-override={overrides.rectangle27}
                  className={classNames(projectcss.all, sty.rectangle27)}
                />

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__yySwd
                  )}
                >
                  {"Available: Yes"}
                </div>
                <div
                  data-plasmic-name={"group21"}
                  data-plasmic-override={overrides.group21}
                  className={classNames(projectcss.all, sty.group21)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__jqpFh)}
                    displayHeight={"32px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"32px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/cruise_crew_iq/images/group17.svg",
                      fullWidth: 32,
                      fullHeight: 32,
                      aspectRatio: 1
                    }}
                  />

                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___2EsC9)}
                    displayHeight={"32px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"32px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/cruise_crew_iq/images/group18.svg",
                      fullWidth: 32,
                      fullHeight: 32,
                      aspectRatio: 1
                    }}
                  />

                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__oU9Ra)}
                    displayHeight={"32px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"32px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/cruise_crew_iq/images/group19.svg",
                      fullWidth: 32,
                      fullHeight: 32,
                      aspectRatio: 1
                    }}
                  />
                </div>
              </div>
              <div
                data-plasmic-name={"room2"}
                data-plasmic-override={overrides.room2}
                className={classNames(projectcss.all, sty.room2)}
              >
                <div
                  data-plasmic-name={"rectangle10"}
                  data-plasmic-override={overrides.rectangle10}
                  className={classNames(projectcss.all, sty.rectangle10)}
                />

                <div
                  data-plasmic-name={"rectangle29"}
                  data-plasmic-override={overrides.rectangle29}
                  className={classNames(projectcss.all, sty.rectangle29)}
                />

                <div
                  data-plasmic-name={"rectangle30"}
                  data-plasmic-override={overrides.rectangle30}
                  className={classNames(projectcss.all, sty.rectangle30)}
                />

                <div
                  data-plasmic-name={"group22"}
                  data-plasmic-override={overrides.group22}
                  className={classNames(projectcss.all, sty.group22)}
                >
                  <div
                    data-plasmic-name={"rectangle31"}
                    data-plasmic-override={overrides.rectangle31}
                    className={classNames(projectcss.all, sty.rectangle31)}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__sgUfx
                    )}
                  >
                    {"Book now"}
                  </div>
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___3IvRh
                  )}
                >
                  {"The Royal Room"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__b4DIq
                  )}
                >
                  {"\u20a6190,000"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__qiN4G
                  )}
                >
                  {"Available: Yes"}
                </div>
                <div
                  data-plasmic-name={"group23"}
                  data-plasmic-override={overrides.group23}
                  className={classNames(projectcss.all, sty.group23)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__e3C8D)}
                    displayHeight={"32px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"32px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/cruise_crew_iq/images/group17.svg",
                      fullWidth: 32,
                      fullHeight: 32,
                      aspectRatio: 1
                    }}
                  />

                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__sJwNb)}
                    displayHeight={"32px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"32px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/cruise_crew_iq/images/group18.svg",
                      fullWidth: 32,
                      fullHeight: 32,
                      aspectRatio: 1
                    }}
                  />

                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__hWspQ)}
                    displayHeight={"32px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"32px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/cruise_crew_iq/images/group19.svg",
                      fullWidth: 32,
                      fullHeight: 32,
                      aspectRatio: 1
                    }}
                  />
                </div>
              </div>
              <div
                data-plasmic-name={"room3"}
                data-plasmic-override={overrides.room3}
                className={classNames(projectcss.all, sty.room3)}
              >
                <div
                  data-plasmic-name={"rectangle11"}
                  data-plasmic-override={overrides.rectangle11}
                  className={classNames(projectcss.all, sty.rectangle11)}
                />

                <div
                  data-plasmic-name={"rectangle32"}
                  data-plasmic-override={overrides.rectangle32}
                  className={classNames(projectcss.all, sty.rectangle32)}
                />

                <div
                  data-plasmic-name={"rectangle33"}
                  data-plasmic-override={overrides.rectangle33}
                  className={classNames(projectcss.all, sty.rectangle33)}
                />

                <div
                  data-plasmic-name={"group24"}
                  data-plasmic-override={overrides.group24}
                  className={classNames(projectcss.all, sty.group24)}
                >
                  <div
                    data-plasmic-name={"rectangle34"}
                    data-plasmic-override={overrides.rectangle34}
                    className={classNames(projectcss.all, sty.rectangle34)}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__iyGEo
                    )}
                  >
                    {"Book now"}
                  </div>
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__o4QOi
                  )}
                >
                  {"The Royal Room"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__vhw8G
                  )}
                >
                  {"\u20a6190,000"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__soPu
                  )}
                >
                  {"Available: Yes"}
                </div>
                <div
                  data-plasmic-name={"group25"}
                  data-plasmic-override={overrides.group25}
                  className={classNames(projectcss.all, sty.group25)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__bt3EF)}
                    displayHeight={"32px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"32px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/cruise_crew_iq/images/group17.svg",
                      fullWidth: 32,
                      fullHeight: 32,
                      aspectRatio: 1
                    }}
                  />

                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__uWj4D)}
                    displayHeight={"32px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"32px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/cruise_crew_iq/images/group18.svg",
                      fullWidth: 32,
                      fullHeight: 32,
                      aspectRatio: 1
                    }}
                  />

                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__kNGa7)}
                    displayHeight={"32px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"32px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/cruise_crew_iq/images/group19.svg",
                      fullWidth: 32,
                      fullHeight: 32,
                      aspectRatio: 1
                    }}
                  />
                </div>
              </div>
              <div
                data-plasmic-name={"room4"}
                data-plasmic-override={overrides.room4}
                className={classNames(projectcss.all, sty.room4)}
              >
                <div
                  data-plasmic-name={"rectangle12"}
                  data-plasmic-override={overrides.rectangle12}
                  className={classNames(projectcss.all, sty.rectangle12)}
                />

                <div
                  data-plasmic-name={"rectangle35"}
                  data-plasmic-override={overrides.rectangle35}
                  className={classNames(projectcss.all, sty.rectangle35)}
                />

                <div
                  data-plasmic-name={"rectangle36"}
                  data-plasmic-override={overrides.rectangle36}
                  className={classNames(projectcss.all, sty.rectangle36)}
                />

                <div
                  data-plasmic-name={"group26"}
                  data-plasmic-override={overrides.group26}
                  className={classNames(projectcss.all, sty.group26)}
                >
                  <div
                    data-plasmic-name={"rectangle37"}
                    data-plasmic-override={overrides.rectangle37}
                    className={classNames(projectcss.all, sty.rectangle37)}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__fhcDq
                    )}
                  >
                    {"Book now"}
                  </div>
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__kypN9
                  )}
                >
                  {"The Royal Room"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__rWyZh
                  )}
                >
                  {"\u20a6190,000"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___0JG8N
                  )}
                >
                  {"Available: Yes"}
                </div>
                <div
                  data-plasmic-name={"group27"}
                  data-plasmic-override={overrides.group27}
                  className={classNames(projectcss.all, sty.group27)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__kPmTw)}
                    displayHeight={"32px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"32px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/cruise_crew_iq/images/group17.svg",
                      fullWidth: 32,
                      fullHeight: 32,
                      aspectRatio: 1
                    }}
                  />

                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__eVfC5)}
                    displayHeight={"32px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"32px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/cruise_crew_iq/images/group18.svg",
                      fullWidth: 32,
                      fullHeight: 32,
                      aspectRatio: 1
                    }}
                  />

                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___8QTxg)}
                    displayHeight={"32px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"32px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/cruise_crew_iq/images/group19.svg",
                      fullWidth: 32,
                      fullHeight: 32,
                      aspectRatio: 1
                    }}
                  />
                </div>
              </div>
              <div
                data-plasmic-name={"room5"}
                data-plasmic-override={overrides.room5}
                className={classNames(projectcss.all, sty.room5)}
              >
                <div
                  data-plasmic-name={"rectangle13"}
                  data-plasmic-override={overrides.rectangle13}
                  className={classNames(projectcss.all, sty.rectangle13)}
                />

                <div
                  data-plasmic-name={"rectangle38"}
                  data-plasmic-override={overrides.rectangle38}
                  className={classNames(projectcss.all, sty.rectangle38)}
                />

                <div
                  data-plasmic-name={"rectangle39"}
                  data-plasmic-override={overrides.rectangle39}
                  className={classNames(projectcss.all, sty.rectangle39)}
                />

                <div
                  data-plasmic-name={"group28"}
                  data-plasmic-override={overrides.group28}
                  className={classNames(projectcss.all, sty.group28)}
                >
                  <div
                    data-plasmic-name={"rectangle40"}
                    data-plasmic-override={overrides.rectangle40}
                    className={classNames(projectcss.all, sty.rectangle40)}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qWnfR
                    )}
                  >
                    {"Book now"}
                  </div>
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__pknb5
                  )}
                >
                  {"The Royal Room"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__kmEgx
                  )}
                >
                  {"\u20a6190,000"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__sd0IV
                  )}
                >
                  {"Available: Yes"}
                </div>
                <div
                  data-plasmic-name={"group29"}
                  data-plasmic-override={overrides.group29}
                  className={classNames(projectcss.all, sty.group29)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___9Uasq)}
                    displayHeight={"32px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"32px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/cruise_crew_iq/images/group17.svg",
                      fullWidth: 32,
                      fullHeight: 32,
                      aspectRatio: 1
                    }}
                  />

                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__dlVk8)}
                    displayHeight={"32px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"32px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/cruise_crew_iq/images/group18.svg",
                      fullWidth: 32,
                      fullHeight: 32,
                      aspectRatio: 1
                    }}
                  />

                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__oj7M4)}
                    displayHeight={"32px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"32px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/cruise_crew_iq/images/group19.svg",
                      fullWidth: 32,
                      fullHeight: 32,
                      aspectRatio: 1
                    }}
                  />
                </div>
              </div>
              <div
                data-plasmic-name={"room6"}
                data-plasmic-override={overrides.room6}
                className={classNames(projectcss.all, sty.room6)}
              >
                <div
                  data-plasmic-name={"rectangle14"}
                  data-plasmic-override={overrides.rectangle14}
                  className={classNames(projectcss.all, sty.rectangle14)}
                />

                <div
                  data-plasmic-name={"rectangle41"}
                  data-plasmic-override={overrides.rectangle41}
                  className={classNames(projectcss.all, sty.rectangle41)}
                />

                <div
                  data-plasmic-name={"rectangle42"}
                  data-plasmic-override={overrides.rectangle42}
                  className={classNames(projectcss.all, sty.rectangle42)}
                />

                <div
                  data-plasmic-name={"group30"}
                  data-plasmic-override={overrides.group30}
                  className={classNames(projectcss.all, sty.group30)}
                >
                  <div
                    data-plasmic-name={"rectangle43"}
                    data-plasmic-override={overrides.rectangle43}
                    className={classNames(projectcss.all, sty.rectangle43)}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zx14
                    )}
                  >
                    {"Book now"}
                  </div>
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__kHbB
                  )}
                >
                  {"The Royal Room"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__qVv51
                  )}
                >
                  {"\u20a6190,000"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__peOo6
                  )}
                >
                  {"Available: Yes"}
                </div>
                <div
                  data-plasmic-name={"group31"}
                  data-plasmic-override={overrides.group31}
                  className={classNames(projectcss.all, sty.group31)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__a5LXf)}
                    displayHeight={"32px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"32px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/cruise_crew_iq/images/group17.svg",
                      fullWidth: 32,
                      fullHeight: 32,
                      aspectRatio: 1
                    }}
                  />

                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__rQpLd)}
                    displayHeight={"32px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"32px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/cruise_crew_iq/images/group18.svg",
                      fullWidth: 32,
                      fullHeight: 32,
                      aspectRatio: 1
                    }}
                  />

                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__mPxGx)}
                    displayHeight={"32px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"32px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/cruise_crew_iq/images/group19.svg",
                      fullWidth: 32,
                      fullHeight: 32,
                      aspectRatio: 1
                    }}
                  />
                </div>
              </div>
            </Stack__>
          </Stack__>
          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  rooms: [
    "rooms",
    "navbar",
    "hero",
    "textInfo",
    "scrollDown",
    "svg",
    "rectangle25",
    "frame279",
    "frame280",
    "room1",
    "rectangle9",
    "rectangle26",
    "group20",
    "rectangle28",
    "rectangle27",
    "group21",
    "room2",
    "rectangle10",
    "rectangle29",
    "rectangle30",
    "group22",
    "rectangle31",
    "group23",
    "room3",
    "rectangle11",
    "rectangle32",
    "rectangle33",
    "group24",
    "rectangle34",
    "group25",
    "room4",
    "rectangle12",
    "rectangle35",
    "rectangle36",
    "group26",
    "rectangle37",
    "group27",
    "room5",
    "rectangle13",
    "rectangle38",
    "rectangle39",
    "group28",
    "rectangle40",
    "group29",
    "room6",
    "rectangle14",
    "rectangle41",
    "rectangle42",
    "group30",
    "rectangle43",
    "group31",
    "footer"
  ],
  navbar: ["navbar"],
  hero: ["hero", "textInfo", "scrollDown", "svg", "rectangle25"],
  textInfo: ["textInfo", "scrollDown", "svg", "rectangle25"],
  scrollDown: ["scrollDown", "svg", "rectangle25"],
  svg: ["svg"],
  rectangle25: ["rectangle25"],
  frame279: [
    "frame279",
    "frame280",
    "room1",
    "rectangle9",
    "rectangle26",
    "group20",
    "rectangle28",
    "rectangle27",
    "group21",
    "room2",
    "rectangle10",
    "rectangle29",
    "rectangle30",
    "group22",
    "rectangle31",
    "group23",
    "room3",
    "rectangle11",
    "rectangle32",
    "rectangle33",
    "group24",
    "rectangle34",
    "group25",
    "room4",
    "rectangle12",
    "rectangle35",
    "rectangle36",
    "group26",
    "rectangle37",
    "group27",
    "room5",
    "rectangle13",
    "rectangle38",
    "rectangle39",
    "group28",
    "rectangle40",
    "group29",
    "room6",
    "rectangle14",
    "rectangle41",
    "rectangle42",
    "group30",
    "rectangle43",
    "group31"
  ],
  frame280: [
    "frame280",
    "room1",
    "rectangle9",
    "rectangle26",
    "group20",
    "rectangle28",
    "rectangle27",
    "group21",
    "room2",
    "rectangle10",
    "rectangle29",
    "rectangle30",
    "group22",
    "rectangle31",
    "group23",
    "room3",
    "rectangle11",
    "rectangle32",
    "rectangle33",
    "group24",
    "rectangle34",
    "group25",
    "room4",
    "rectangle12",
    "rectangle35",
    "rectangle36",
    "group26",
    "rectangle37",
    "group27",
    "room5",
    "rectangle13",
    "rectangle38",
    "rectangle39",
    "group28",
    "rectangle40",
    "group29",
    "room6",
    "rectangle14",
    "rectangle41",
    "rectangle42",
    "group30",
    "rectangle43",
    "group31"
  ],
  room1: [
    "room1",
    "rectangle9",
    "rectangle26",
    "group20",
    "rectangle28",
    "rectangle27",
    "group21"
  ],
  rectangle9: ["rectangle9"],
  rectangle26: ["rectangle26"],
  group20: ["group20", "rectangle28"],
  rectangle28: ["rectangle28"],
  rectangle27: ["rectangle27"],
  group21: ["group21"],
  room2: [
    "room2",
    "rectangle10",
    "rectangle29",
    "rectangle30",
    "group22",
    "rectangle31",
    "group23"
  ],
  rectangle10: ["rectangle10"],
  rectangle29: ["rectangle29"],
  rectangle30: ["rectangle30"],
  group22: ["group22", "rectangle31"],
  rectangle31: ["rectangle31"],
  group23: ["group23"],
  room3: [
    "room3",
    "rectangle11",
    "rectangle32",
    "rectangle33",
    "group24",
    "rectangle34",
    "group25"
  ],
  rectangle11: ["rectangle11"],
  rectangle32: ["rectangle32"],
  rectangle33: ["rectangle33"],
  group24: ["group24", "rectangle34"],
  rectangle34: ["rectangle34"],
  group25: ["group25"],
  room4: [
    "room4",
    "rectangle12",
    "rectangle35",
    "rectangle36",
    "group26",
    "rectangle37",
    "group27"
  ],
  rectangle12: ["rectangle12"],
  rectangle35: ["rectangle35"],
  rectangle36: ["rectangle36"],
  group26: ["group26", "rectangle37"],
  rectangle37: ["rectangle37"],
  group27: ["group27"],
  room5: [
    "room5",
    "rectangle13",
    "rectangle38",
    "rectangle39",
    "group28",
    "rectangle40",
    "group29"
  ],
  rectangle13: ["rectangle13"],
  rectangle38: ["rectangle38"],
  rectangle39: ["rectangle39"],
  group28: ["group28", "rectangle40"],
  rectangle40: ["rectangle40"],
  group29: ["group29"],
  room6: [
    "room6",
    "rectangle14",
    "rectangle41",
    "rectangle42",
    "group30",
    "rectangle43",
    "group31"
  ],
  rectangle14: ["rectangle14"],
  rectangle41: ["rectangle41"],
  rectangle42: ["rectangle42"],
  group30: ["group30", "rectangle43"],
  rectangle43: ["rectangle43"],
  group31: ["group31"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  rooms: "div";
  navbar: typeof Navbar;
  hero: "div";
  textInfo: "div";
  scrollDown: "div";
  svg: "svg";
  rectangle25: "div";
  frame279: "div";
  frame280: "div";
  room1: "div";
  rectangle9: "div";
  rectangle26: "div";
  group20: "div";
  rectangle28: "div";
  rectangle27: "div";
  group21: "div";
  room2: "div";
  rectangle10: "div";
  rectangle29: "div";
  rectangle30: "div";
  group22: "div";
  rectangle31: "div";
  group23: "div";
  room3: "div";
  rectangle11: "div";
  rectangle32: "div";
  rectangle33: "div";
  group24: "div";
  rectangle34: "div";
  group25: "div";
  room4: "div";
  rectangle12: "div";
  rectangle35: "div";
  rectangle36: "div";
  group26: "div";
  rectangle37: "div";
  group27: "div";
  room5: "div";
  rectangle13: "div";
  rectangle38: "div";
  rectangle39: "div";
  group28: "div";
  rectangle40: "div";
  group29: "div";
  room6: "div";
  rectangle14: "div";
  rectangle41: "div";
  rectangle42: "div";
  group30: "div";
  rectangle43: "div";
  group31: "div";
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicRooms__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicRooms__VariantsArgs;
    args?: PlasmicRooms__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicRooms__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicRooms__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicRooms__ArgProps,
          internalVariantPropNames: PlasmicRooms__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicRooms__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "rooms") {
    func.displayName = "PlasmicRooms";
  } else {
    func.displayName = `PlasmicRooms.${nodeName}`;
  }
  return func;
}

function withUsePlasmicAuth<P extends object>(
  WrappedComponent: React.ComponentType<P>
) {
  const WithUsePlasmicAuthComponent: React.FC<P> = props => {
    const dataSourceCtx = usePlasmicDataSourceContext() ?? {};
    const { isUserLoading, user, token } = plasmicAuth.usePlasmicAuth({
      appId: "r6SzurXsLMJXPqEBWV3sKk"
    });

    return (
      <PlasmicDataSourceContextProvider__
        value={{
          ...dataSourceCtx,
          isUserLoading,
          userAuthToken: token,
          user
        }}
      >
        <WrappedComponent {...props} />
      </PlasmicDataSourceContextProvider__>
    );
  };
  return WithUsePlasmicAuthComponent;
}

export const PlasmicRooms = Object.assign(
  // Top-level PlasmicRooms renders the root element
  withUsePlasmicAuth(makeNodeComponent("rooms")),
  {
    // Helper components rendering sub-elements
    navbar: makeNodeComponent("navbar"),
    hero: makeNodeComponent("hero"),
    textInfo: makeNodeComponent("textInfo"),
    scrollDown: makeNodeComponent("scrollDown"),
    svg: makeNodeComponent("svg"),
    rectangle25: makeNodeComponent("rectangle25"),
    frame279: makeNodeComponent("frame279"),
    frame280: makeNodeComponent("frame280"),
    room1: makeNodeComponent("room1"),
    rectangle9: makeNodeComponent("rectangle9"),
    rectangle26: makeNodeComponent("rectangle26"),
    group20: makeNodeComponent("group20"),
    rectangle28: makeNodeComponent("rectangle28"),
    rectangle27: makeNodeComponent("rectangle27"),
    group21: makeNodeComponent("group21"),
    room2: makeNodeComponent("room2"),
    rectangle10: makeNodeComponent("rectangle10"),
    rectangle29: makeNodeComponent("rectangle29"),
    rectangle30: makeNodeComponent("rectangle30"),
    group22: makeNodeComponent("group22"),
    rectangle31: makeNodeComponent("rectangle31"),
    group23: makeNodeComponent("group23"),
    room3: makeNodeComponent("room3"),
    rectangle11: makeNodeComponent("rectangle11"),
    rectangle32: makeNodeComponent("rectangle32"),
    rectangle33: makeNodeComponent("rectangle33"),
    group24: makeNodeComponent("group24"),
    rectangle34: makeNodeComponent("rectangle34"),
    group25: makeNodeComponent("group25"),
    room4: makeNodeComponent("room4"),
    rectangle12: makeNodeComponent("rectangle12"),
    rectangle35: makeNodeComponent("rectangle35"),
    rectangle36: makeNodeComponent("rectangle36"),
    group26: makeNodeComponent("group26"),
    rectangle37: makeNodeComponent("rectangle37"),
    group27: makeNodeComponent("group27"),
    room5: makeNodeComponent("room5"),
    rectangle13: makeNodeComponent("rectangle13"),
    rectangle38: makeNodeComponent("rectangle38"),
    rectangle39: makeNodeComponent("rectangle39"),
    group28: makeNodeComponent("group28"),
    rectangle40: makeNodeComponent("rectangle40"),
    group29: makeNodeComponent("group29"),
    room6: makeNodeComponent("room6"),
    rectangle14: makeNodeComponent("rectangle14"),
    rectangle41: makeNodeComponent("rectangle41"),
    rectangle42: makeNodeComponent("rectangle42"),
    group30: makeNodeComponent("group30"),
    rectangle43: makeNodeComponent("rectangle43"),
    group31: makeNodeComponent("group31"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicRooms
    internalVariantProps: PlasmicRooms__VariantProps,
    internalArgProps: PlasmicRooms__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicRooms;
/* prettier-ignore-end */
