services:
  db:
    image: postgres:16.4-alpine3.20
    container_name: Cruise-Crew-IQ-db
    ports:
      - $DB_PORT:5432
    environment:
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_DATABASE
